language: node_js

node_js: stable

cache: node_modules

before_install: yarn global add greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn test

after_script: greenkeeper-lockfile-upload
